### ISSUE TITLE
Long OSM IDs cause integer issue and NA.

### ISSUE THREAD

**Issue by lshydro** [dieghernan/nominatimlite#47]
The function geo_address_lookup results in `NAs introduced by coercion to integer range` due to exceeding the R internal integer limit `.Machine$integer.max` = 2147483647. 
This problem originates in the step `osm_ids <- as.integer(osm_ids)`. 
Reproducible example: 
`geo_address_lookup(osm_ids = c(9743343761), type = "N", full_results = T)`
My current workaround is to just skip the `as.integer(osm_ids)` step, though this it only work if I know for sure the input are numeric.

**Comment by dieghernan** [comment]
Thanks @lshydro  for reporting and investigating. It should be closed in the dev version after merging #48
